<script src="https://kit.fontawesome.com/357c4141d9.js" crossorigin="anonymous"></script>
<div class="container-fluid h-100">
	<div class="row h-100">
    
    <div class="col-md-6 banner">
    	<div class="row h-100 justify-content-center align-items-center">
    		<div>
				<div class="communicationItem">
					<i class="fas fa-search fa-2x mr-3"></i>
					Siga o que lhe interessa.
				</div>
				<div class="communicationItem">
					<i class="fas fa-user-friends fa-2x mr-3"></i>
					Saiba sobre o que as pessoas estão falando.
				</div>
				<div class="communicationItem">
					<i class="far fa-comment fa-2x mr-3"></i>
					Participe da conversa.
				</div>
			</div>
		</div>
    </div>

    <div class="col-md-6 pt-4 pl-5 pr-5">
		<form action='/autenticar' method='post'>
			<div class="row">
				<div class="col">
					<input type="text" class="form-control" placeholder="E-mail" name="email">
				</div>
				<div class="col input-group">
					<input type="password" class="form-control oculta" placeholder="Senha" name="senha" id="senha" style="background:">
					<span class="input-group-addon">
						<button type="button" class="fa-solid fa-eye" style="background:transparent;border:none;margin-top: 30%;" id="botaoSenha"></button>
					</span>
				</div>
				<div class="col-auto">
					<button type="submit" class="btn btn-primary mb-2">Entrar</button>
				</div>
			</div>
			<?php if($this->view->login == 'erro'){;?>
				<div class="row">
					<div class="col">
						<span class="text text-danger">*Email e ou senha inválidos</span>
					</div>
				</div>
			<?php } ?>
		</form>

		<div class="row pt-5 pl-5 pr-5">
			<div class="col pl-5 pr-5">
				<img src="/img/twitter_logo.png" />
				<h1 class="title">Veja o que está acontecendo no mundo agora</h1>

				<h2 class="mt-5 subtitle">Participe hoje do Twitter.</h2>
				<a href="/inscreverse" class="btn btn-primary btn-block mb-2">Inscrever-se</a>
			</div>	
		</div>

    </div>

  </div>
</div>
<script>
	$("#botaoSenha").on('click', ()=>{
		$("#botaoSenha").toggleClass('fa-solid fa-eye-slash fa-solid fa-eye');

		if(document.getElementById("senha").classList == 'form-control'){
			console.log(document.getElementById("senha").classList)
			document.getElementById("senha").classList.add('oculta')
			document.getElementById("senha").type = 'password'
		}else{
			console.log(document.getElementById("senha").classList)
			document.getElementById("senha").classList.remove('oculta')
			document.getElementById("senha").type = 'text'
		}
	
		//document.getElementById("senha").type = 'password'
		//document.getElementById("senha").classList.add('teste')

		
	})
</script>