<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="d-flex justify-content-center">
          <img src="/img/twitter_logo.png" />
        </div>

        <div class="row">
          <div class="col">
            <h2>Crie sua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/registrar" method="post">
              <div class="form-group">
                <input type="text" value="<?= $this->view->usuario['nome'] ?>" name="nome" class="form-control <?php if($this->view->nameUser){echo'is-invalid';}?>" placeholder="Nome">
                <div class='invalid-feedback'>
                  Esse nome de usuario ja existe
                </div>
              </div>
              
              <div class="form-group">
                <input type="text" value="<?=$this->view->usuario['email']?>" name="email" class="form-control <?php if($this->view->emailUser){echo'is-invalid';}?>" placeholder="E-mail">
                <div class='invalid-feedback'>
                  Esse email ja existe
                </div>
              </div>

              <div class="form-group">
                <input type="password" value="<?=$this->view->usuario['senha']?>" name="senha" class="form-control" placeholder="Senha" id='senha'  onkeypress="validaSenha()">
                <div class='invalid-feedback' id='feedback'>
                  Senha precisa ter mais de 8 caracteres
                </div>
              </div>
              
              <div class="mt-4 mb-4">
                <small class="form-text">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                </small>
              </div>
              <button type="submit" class="btn btn-primary btn-block">Inscrever-se</button>
              <?php if($this->view->erroCadastro){?>

                <small class="form-text text-danger">
                  *Erro ao tentar realizar o cadastro, verifique se você preencheu corretamente os campos
                </small>

              <?php }?>
            </form>

          </div>
        </div>

      </div>
    </div>
  </div>
</div>
<script>
  let senha = document.getElementById('senha');
  let feedback = document.getElementById('feedback');
  let senhaValue = document.getElementById('senha').value;
  function validaSenha(){
    console.log(senha.value.length)
    if(senha.value.length < 7 ){
      senha.classList.add('is-invalid')
      feedback.classList.add('invalid-feedback')
      senha.classList.remove('is-valid')
      feedback.classList.remove('valid-feedback')
    } else {
      senha.classList.remove('is-invalid')
      feedback.classList.remove('invalid-feedback')
      senha.classList.add('is-valid')
      feedback.classList.add('valid-feedback')
    }
  }
</script>


    
  